### ISSUE TITLE
Notebook and get_roi()

### ISSUE THREAD

**Issue by ehodneland** [erling6232/imagedata#57]
Hi, when using

s.get_roi()

I get the following error message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 im.get_roi()

File ~/anaconda3/lib/python3.9/site-packages/imagedata/series.py:2557, in Series.get_roi(self, roi, color, follow, vertices, im2, fig, ax, colormap, norm, colorbar, window, level, link, single, onselect)
   2555 except AssertionError:
   2556     raise
-> 2557 self.viewer.connect_draw(roi=roi, color=color)
   2558 plt.tight_layout()
   2559 plt.show()

File ~/anaconda3/lib/python3.9/site-packages/imagedata/viewer.py:248, in Viewer.connect_draw(self, roi, color, callback_quit)
    243         self.poly[0, idx] = MyPolygonSelector(self.ax[0, 0], self.onselect,
    244                                               lineprops={'color': self.poly_color},
    245                                               tag=(0, idx), copy=self.on_copy,
    246                                               paste=self.on_paste)
    247     else:
--> 248         self.poly[idx] = MyPolygonSelector(self.ax[0, 0], self.onselect,
    249                                            lineprops={'color': self.poly_color},
    250                                            tag=idx, copy=self.on_copy, paste=self.on_paste)
    251 else:
    252     self.poly = {}

File ~/anaconda3/lib/python3.9/site-packages/imagedata/viewer.py:659, in MyPolygonSelector.__init__(self, ax, onselect, useblit, lineprops, markerprops, vertex_select_radius, vertices, tag, copy, paste)
    656 def __init__(self, ax, onselect, useblit=False,
    657              lineprops=None, markerprops=None, vertex_select_radius=15,
    658              vertices=None, tag=None, copy=None, paste=None):
--> 659     super().__init__(ax, onselect, useblit=useblit,
    660                      lineprops=lineprops, markerprops=markerprops,
    661                      vertex_select_radius=vertex_select_radius)
    663     self.tag = tag
    664     self.copy_handle = copy

File ~/anaconda3/lib/python3.9/site-packages/matplotlib/_api/deprecation.py:454, in make_keyword_only.<locals>.wrapper(*args, **kwargs)
    448 if len(args) > name_idx:
    449     warn_deprecated(
    450         since, message="Passing the %(name)s %(obj_type)s "
    451         "positionally is deprecated since Matplotlib %(since)s; the "
    452         "parameter will become keyword-only %(removal)s.",
    453         name=name, obj_type=f"parameter of {func.__name__}()")
--> 454 return func(*args, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'lineprops'

I am using matplotlib version 3.8.1

**Comment by erling6232** [comment]
Fixed in imagedata version 3.2.3.
